/*
* generated by Xtext
*/
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractHighwayProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HighwayProposalProvider extends AbstractHighwayProposalProvider {

}
