/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.HighwayActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HighwayExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HighwayActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HighwayActivator.getInstance().getInjector(HighwayActivator.ORG_XTEXT_HIGHWAY);
	}
	
}
