/*
* generated by Xtext
*/

package org.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class HighwayGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class HighwayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Highway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHighwayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHighwayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSegmentsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cInitSegmentsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cInitSegmentsSegmentParserRuleCall_3_2_0 = (RuleCall)cInitSegmentsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cInitSegmentsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cInitSegmentsSegmentParserRuleCall_3_3_1_0 = (RuleCall)cInitSegmentsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNodesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cInitNodesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cInitNodesNodeParserRuleCall_4_2_0 = (RuleCall)cInitNodesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cInitNodesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cInitNodesNodeParserRuleCall_4_3_1_0 = (RuleCall)cInitNodesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCarsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cInitCarsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cInitCarsCarParserRuleCall_5_2_0 = (RuleCall)cInitCarsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cInitCarsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cInitCarsCarParserRuleCall_5_3_1_0 = (RuleCall)cInitCarsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSemaphoresKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInitSemaphoreAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cInitSemaphoreSemaphoreParserRuleCall_6_2_0 = (RuleCall)cInitSemaphoreAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cInitSemaphoreAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cInitSemaphoreSemaphoreParserRuleCall_6_3_1_0 = (RuleCall)cInitSemaphoreAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSignalsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cInitSignalAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cInitSignalSignalParserRuleCall_7_2_0 = (RuleCall)cInitSignalAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cInitSignalAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cInitSignalSignalParserRuleCall_7_3_1_0 = (RuleCall)cInitSignalAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Highway:
		//
		//	{Highway} "Highway" "{" ("Segments" "{" initSegments+=Segment ("," initSegments+=Segment)* "}")? ("Nodes" "{"
		//
		//	initNodes+=Node ("," initNodes+=Node)* "}")? ("Cars" "{" initCars+=Car ("," initCars+=Car)* "}")? ("Semaphores" "{"
		//
		//	initSemaphore+=Semaphore ("," initSemaphore+=Semaphore)* "}")? ("Signals" "{" initSignal+=Signal (","
		//
		//	initSignal+=Signal)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Highway} "Highway" "{" ("Segments" "{" initSegments+=Segment ("," initSegments+=Segment)* "}")? ("Nodes" "{"
		//
		//initNodes+=Node ("," initNodes+=Node)* "}")? ("Cars" "{" initCars+=Car ("," initCars+=Car)* "}")? ("Semaphores" "{"
		//
		//initSemaphore+=Semaphore ("," initSemaphore+=Semaphore)* "}")? ("Signals" "{" initSignal+=Signal (","
		//
		//initSignal+=Signal)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Highway}
		public Action getHighwayAction_0() { return cHighwayAction_0; }

		//"Highway"
		public Keyword getHighwayKeyword_1() { return cHighwayKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("Segments" "{" initSegments+=Segment ("," initSegments+=Segment)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"Segments"
		public Keyword getSegmentsKeyword_3_0() { return cSegmentsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//initSegments+=Segment
		public Assignment getInitSegmentsAssignment_3_2() { return cInitSegmentsAssignment_3_2; }

		//Segment
		public RuleCall getInitSegmentsSegmentParserRuleCall_3_2_0() { return cInitSegmentsSegmentParserRuleCall_3_2_0; }

		//("," initSegments+=Segment)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//initSegments+=Segment
		public Assignment getInitSegmentsAssignment_3_3_1() { return cInitSegmentsAssignment_3_3_1; }

		//Segment
		public RuleCall getInitSegmentsSegmentParserRuleCall_3_3_1_0() { return cInitSegmentsSegmentParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("Nodes" "{" initNodes+=Node ("," initNodes+=Node)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"Nodes"
		public Keyword getNodesKeyword_4_0() { return cNodesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//initNodes+=Node
		public Assignment getInitNodesAssignment_4_2() { return cInitNodesAssignment_4_2; }

		//Node
		public RuleCall getInitNodesNodeParserRuleCall_4_2_0() { return cInitNodesNodeParserRuleCall_4_2_0; }

		//("," initNodes+=Node)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//initNodes+=Node
		public Assignment getInitNodesAssignment_4_3_1() { return cInitNodesAssignment_4_3_1; }

		//Node
		public RuleCall getInitNodesNodeParserRuleCall_4_3_1_0() { return cInitNodesNodeParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("Cars" "{" initCars+=Car ("," initCars+=Car)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"Cars"
		public Keyword getCarsKeyword_5_0() { return cCarsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//initCars+=Car
		public Assignment getInitCarsAssignment_5_2() { return cInitCarsAssignment_5_2; }

		//Car
		public RuleCall getInitCarsCarParserRuleCall_5_2_0() { return cInitCarsCarParserRuleCall_5_2_0; }

		//("," initCars+=Car)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//initCars+=Car
		public Assignment getInitCarsAssignment_5_3_1() { return cInitCarsAssignment_5_3_1; }

		//Car
		public RuleCall getInitCarsCarParserRuleCall_5_3_1_0() { return cInitCarsCarParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("Semaphores" "{" initSemaphore+=Semaphore ("," initSemaphore+=Semaphore)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"Semaphores"
		public Keyword getSemaphoresKeyword_6_0() { return cSemaphoresKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//initSemaphore+=Semaphore
		public Assignment getInitSemaphoreAssignment_6_2() { return cInitSemaphoreAssignment_6_2; }

		//Semaphore
		public RuleCall getInitSemaphoreSemaphoreParserRuleCall_6_2_0() { return cInitSemaphoreSemaphoreParserRuleCall_6_2_0; }

		//("," initSemaphore+=Semaphore)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//initSemaphore+=Semaphore
		public Assignment getInitSemaphoreAssignment_6_3_1() { return cInitSemaphoreAssignment_6_3_1; }

		//Semaphore
		public RuleCall getInitSemaphoreSemaphoreParserRuleCall_6_3_1_0() { return cInitSemaphoreSemaphoreParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("Signals" "{" initSignal+=Signal ("," initSignal+=Signal)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"Signals"
		public Keyword getSignalsKeyword_7_0() { return cSignalsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//initSignal+=Signal
		public Assignment getInitSignalAssignment_7_2() { return cInitSignalAssignment_7_2; }

		//Signal
		public RuleCall getInitSignalSignalParserRuleCall_7_2_0() { return cInitSignalSignalParserRuleCall_7_2_0; }

		//("," initSignal+=Signal)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//initSignal+=Signal
		public Assignment getInitSignalAssignment_7_3_1() { return cInitSignalAssignment_7_3_1; }

		//Signal
		public RuleCall getInitSignalSignalParserRuleCall_7_3_1_0() { return cInitSignalSignalParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Node");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNode_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExtractorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInjectorParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Node:
		//
		//	Node_Impl | Extractor | Injector;
		public ParserRule getRule() { return rule; }

		//Node_Impl | Extractor | Injector
		public Alternatives getAlternatives() { return cAlternatives; }

		//Node_Impl
		public RuleCall getNode_ImplParserRuleCall_0() { return cNode_ImplParserRuleCall_0; }

		//Extractor
		public RuleCall getExtractorParserRuleCall_1() { return cExtractorParserRuleCall_1; }

		//Injector
		public RuleCall getInjectorParserRuleCall_2() { return cInjectorParserRuleCall_2; }
	}

	public class SignalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Signal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSignal_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSpeedlimitParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStopParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cYieldParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Signal:
		//
		//	Signal_Impl | Speedlimit | Stop | Yield;
		public ParserRule getRule() { return rule; }

		//Signal_Impl | Speedlimit | Stop | Yield
		public Alternatives getAlternatives() { return cAlternatives; }

		//Signal_Impl
		public RuleCall getSignal_ImplParserRuleCall_0() { return cSignal_ImplParserRuleCall_0; }

		//Speedlimit
		public RuleCall getSpeedlimitParserRuleCall_1() { return cSpeedlimitParserRuleCall_1; }

		//Stop
		public RuleCall getStopParserRuleCall_2() { return cStopParserRuleCall_2; }

		//Yield
		public RuleCall getYieldParserRuleCall_3() { return cYieldParserRuleCall_3; }
	}

	public class Node_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Node_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cHasStartsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHasStartsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cHasStartsSegmentCrossReference_6_0 = (CrossReference)cHasStartsAssignment_6.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_6_0_1 = (RuleCall)cHasStartsSegmentCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cHasStartsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cHasStartsSegmentCrossReference_7_1_0 = (CrossReference)cHasStartsAssignment_7_1.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_7_1_0_1 = (RuleCall)cHasStartsSegmentCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cHasEndsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cHasEndsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cHasEndsSegmentCrossReference_11_0 = (CrossReference)cHasEndsAssignment_11.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_11_0_1 = (RuleCall)cHasEndsSegmentCrossReference_11_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cHasEndsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cHasEndsSegmentCrossReference_12_1_0 = (CrossReference)cHasEndsAssignment_12_1.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_12_1_0_1 = (RuleCall)cHasEndsSegmentCrossReference_12_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cSemaphoreKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cSemaphoreAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final CrossReference cSemaphoreSemaphoreCrossReference_14_1_0 = (CrossReference)cSemaphoreAssignment_14_1.eContents().get(0);
		private final RuleCall cSemaphoreSemaphoreEStringParserRuleCall_14_1_0_1 = (RuleCall)cSemaphoreSemaphoreCrossReference_14_1_0.eContents().get(1);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cSignalsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cSignalsAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final CrossReference cSignalsSignalCrossReference_15_2_0 = (CrossReference)cSignalsAssignment_15_2.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_15_2_0_1 = (RuleCall)cSignalsSignalCrossReference_15_2_0.eContents().get(1);
		private final Group cGroup_15_3 = (Group)cGroup_15.eContents().get(3);
		private final Keyword cCommaKeyword_15_3_0 = (Keyword)cGroup_15_3.eContents().get(0);
		private final Assignment cSignalsAssignment_15_3_1 = (Assignment)cGroup_15_3.eContents().get(1);
		private final CrossReference cSignalsSignalCrossReference_15_3_1_0 = (CrossReference)cSignalsAssignment_15_3_1.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_15_3_1_0_1 = (RuleCall)cSignalsSignalCrossReference_15_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_15_4 = (Keyword)cGroup_15.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Node_Impl returns Node:
		//
		//	{Node} "Node" name=EString "{" "hasStarts" "(" hasStarts+=[Segment|EString] ("," hasStarts+=[Segment|EString])* ")"
		//
		//	"hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")" ("semaphore"
		//
		//	semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Node} "Node" name=EString "{" "hasStarts" "(" hasStarts+=[Segment|EString] ("," hasStarts+=[Segment|EString])* ")"
		//
		//"hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")" ("semaphore"
		//
		//semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Node}
		public Action getNodeAction_0() { return cNodeAction_0; }

		//"Node"
		public Keyword getNodeKeyword_1() { return cNodeKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"hasStarts"
		public Keyword getHasStartsKeyword_4() { return cHasStartsKeyword_4; }

		//"("
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_6() { return cHasStartsAssignment_6; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_6_0() { return cHasStartsSegmentCrossReference_6_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_6_0_1() { return cHasStartsSegmentEStringParserRuleCall_6_0_1; }

		//("," hasStarts+=[Segment|EString])*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_7_1() { return cHasStartsAssignment_7_1; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_7_1_0() { return cHasStartsSegmentCrossReference_7_1_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_7_1_0_1() { return cHasStartsSegmentEStringParserRuleCall_7_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }

		//"hasEnds"
		public Keyword getHasEndsKeyword_9() { return cHasEndsKeyword_9; }

		//"("
		public Keyword getLeftParenthesisKeyword_10() { return cLeftParenthesisKeyword_10; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_11() { return cHasEndsAssignment_11; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_11_0() { return cHasEndsSegmentCrossReference_11_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_11_0_1() { return cHasEndsSegmentEStringParserRuleCall_11_0_1; }

		//("," hasEnds+=[Segment|EString])*
		public Group getGroup_12() { return cGroup_12; }

		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_12_1() { return cHasEndsAssignment_12_1; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_12_1_0() { return cHasEndsSegmentCrossReference_12_1_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_12_1_0_1() { return cHasEndsSegmentEStringParserRuleCall_12_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_13() { return cRightParenthesisKeyword_13; }

		//("semaphore" semaphore=[Semaphore|EString])?
		public Group getGroup_14() { return cGroup_14; }

		//"semaphore"
		public Keyword getSemaphoreKeyword_14_0() { return cSemaphoreKeyword_14_0; }

		//semaphore=[Semaphore|EString]
		public Assignment getSemaphoreAssignment_14_1() { return cSemaphoreAssignment_14_1; }

		//[Semaphore|EString]
		public CrossReference getSemaphoreSemaphoreCrossReference_14_1_0() { return cSemaphoreSemaphoreCrossReference_14_1_0; }

		//EString
		public RuleCall getSemaphoreSemaphoreEStringParserRuleCall_14_1_0_1() { return cSemaphoreSemaphoreEStringParserRuleCall_14_1_0_1; }

		//("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")?
		public Group getGroup_15() { return cGroup_15; }

		//"signals"
		public Keyword getSignalsKeyword_15_0() { return cSignalsKeyword_15_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_15_1() { return cLeftParenthesisKeyword_15_1; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_15_2() { return cSignalsAssignment_15_2; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_15_2_0() { return cSignalsSignalCrossReference_15_2_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_15_2_0_1() { return cSignalsSignalEStringParserRuleCall_15_2_0_1; }

		//("," signals+=[Signal|EString])*
		public Group getGroup_15_3() { return cGroup_15_3; }

		//","
		public Keyword getCommaKeyword_15_3_0() { return cCommaKeyword_15_3_0; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_15_3_1() { return cSignalsAssignment_15_3_1; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_15_3_1_0() { return cSignalsSignalCrossReference_15_3_1_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_15_3_1_0_1() { return cSignalsSignalEStringParserRuleCall_15_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_15_4() { return cRightParenthesisKeyword_15_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class CarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Car");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCarAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCarKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTimeInKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTimeInAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTimeInEDateParserRuleCall_4_1_0 = (RuleCall)cTimeInAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTimeOutKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTimeOutAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTimeOutEDateParserRuleCall_5_1_0 = (RuleCall)cTimeOutAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIsInSegmentKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIsInSegmentAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cIsInSegmentSegmentCrossReference_6_1_0 = (CrossReference)cIsInSegmentAssignment_6_1.eContents().get(0);
		private final RuleCall cIsInSegmentSegmentEStringParserRuleCall_6_1_0_1 = (RuleCall)cIsInSegmentSegmentCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Car:
		//
		//	{Car} "Car" name=EString "{" ("timeIn" timeIn=EDate)? ("timeOut" timeOut=EDate)? ("isInSegment"
		//
		//	isInSegment=[Segment|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Car} "Car" name=EString "{" ("timeIn" timeIn=EDate)? ("timeOut" timeOut=EDate)? ("isInSegment"
		//
		//isInSegment=[Segment|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Car}
		public Action getCarAction_0() { return cCarAction_0; }

		//"Car"
		public Keyword getCarKeyword_1() { return cCarKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("timeIn" timeIn=EDate)?
		public Group getGroup_4() { return cGroup_4; }

		//"timeIn"
		public Keyword getTimeInKeyword_4_0() { return cTimeInKeyword_4_0; }

		//timeIn=EDate
		public Assignment getTimeInAssignment_4_1() { return cTimeInAssignment_4_1; }

		//EDate
		public RuleCall getTimeInEDateParserRuleCall_4_1_0() { return cTimeInEDateParserRuleCall_4_1_0; }

		//("timeOut" timeOut=EDate)?
		public Group getGroup_5() { return cGroup_5; }

		//"timeOut"
		public Keyword getTimeOutKeyword_5_0() { return cTimeOutKeyword_5_0; }

		//timeOut=EDate
		public Assignment getTimeOutAssignment_5_1() { return cTimeOutAssignment_5_1; }

		//EDate
		public RuleCall getTimeOutEDateParserRuleCall_5_1_0() { return cTimeOutEDateParserRuleCall_5_1_0; }

		//("isInSegment" isInSegment=[Segment|EString])?
		public Group getGroup_6() { return cGroup_6; }

		//"isInSegment"
		public Keyword getIsInSegmentKeyword_6_0() { return cIsInSegmentKeyword_6_0; }

		//isInSegment=[Segment|EString]
		public Assignment getIsInSegmentAssignment_6_1() { return cIsInSegmentAssignment_6_1; }

		//[Segment|EString]
		public CrossReference getIsInSegmentSegmentCrossReference_6_1_0() { return cIsInSegmentSegmentCrossReference_6_1_0; }

		//EString
		public RuleCall getIsInSegmentSegmentEStringParserRuleCall_6_1_0_1() { return cIsInSegmentSegmentEStringParserRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class SegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Segment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSegmentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSegmentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNumLanesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNumLanesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNumLanesEIntParserRuleCall_4_1_0 = (RuleCall)cNumLanesAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLengthKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLengthAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLengthEIntParserRuleCall_5_1_0 = (RuleCall)cLengthAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cHasCarsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHasCarsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cHasCarsCarCrossReference_6_2_0 = (CrossReference)cHasCarsAssignment_6_2.eContents().get(0);
		private final RuleCall cHasCarsCarEStringParserRuleCall_6_2_0_1 = (RuleCall)cHasCarsCarCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHasCarsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cHasCarsCarCrossReference_6_3_1_0 = (CrossReference)cHasCarsAssignment_6_3_1.eContents().get(0);
		private final RuleCall cHasCarsCarEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cHasCarsCarCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Segment:
		//
		//	{Segment} "Segment" name=EString "{" ("numLanes" numLanes=EInt)? ("length" length=EInt)? ("hasCars" "("
		//
		//	hasCars+=[Car|EString] ("," hasCars+=[Car|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Segment} "Segment" name=EString "{" ("numLanes" numLanes=EInt)? ("length" length=EInt)? ("hasCars" "("
		//
		//hasCars+=[Car|EString] ("," hasCars+=[Car|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Segment}
		public Action getSegmentAction_0() { return cSegmentAction_0; }

		//"Segment"
		public Keyword getSegmentKeyword_1() { return cSegmentKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("numLanes" numLanes=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"numLanes"
		public Keyword getNumLanesKeyword_4_0() { return cNumLanesKeyword_4_0; }

		//numLanes=EInt
		public Assignment getNumLanesAssignment_4_1() { return cNumLanesAssignment_4_1; }

		//EInt
		public RuleCall getNumLanesEIntParserRuleCall_4_1_0() { return cNumLanesEIntParserRuleCall_4_1_0; }

		//("length" length=EInt)?
		public Group getGroup_5() { return cGroup_5; }

		//"length"
		public Keyword getLengthKeyword_5_0() { return cLengthKeyword_5_0; }

		//length=EInt
		public Assignment getLengthAssignment_5_1() { return cLengthAssignment_5_1; }

		//EInt
		public RuleCall getLengthEIntParserRuleCall_5_1_0() { return cLengthEIntParserRuleCall_5_1_0; }

		//("hasCars" "(" hasCars+=[Car|EString] ("," hasCars+=[Car|EString])* ")")?
		public Group getGroup_6() { return cGroup_6; }

		//"hasCars"
		public Keyword getHasCarsKeyword_6_0() { return cHasCarsKeyword_6_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }

		//hasCars+=[Car|EString]
		public Assignment getHasCarsAssignment_6_2() { return cHasCarsAssignment_6_2; }

		//[Car|EString]
		public CrossReference getHasCarsCarCrossReference_6_2_0() { return cHasCarsCarCrossReference_6_2_0; }

		//EString
		public RuleCall getHasCarsCarEStringParserRuleCall_6_2_0_1() { return cHasCarsCarEStringParserRuleCall_6_2_0_1; }

		//("," hasCars+=[Car|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//hasCars+=[Car|EString]
		public Assignment getHasCarsAssignment_6_3_1() { return cHasCarsAssignment_6_3_1; }

		//[Car|EString]
		public CrossReference getHasCarsCarCrossReference_6_3_1_0() { return cHasCarsCarCrossReference_6_3_1_0; }

		//EString
		public RuleCall getHasCarsCarEStringParserRuleCall_6_3_1_0_1() { return cHasCarsCarEStringParserRuleCall_6_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class SemaphoreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Semaphore");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSemaphoreAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSemaphoreKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCanGoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCanGoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCanGoEBooleanParserRuleCall_4_1_0 = (RuleCall)cCanGoAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSecondsRedKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSecondsRedAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSecondsRedEIntParserRuleCall_5_1_0 = (RuleCall)cSecondsRedAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSecondsGreenKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSecondsGreenAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSecondsGreenEIntParserRuleCall_6_1_0 = (RuleCall)cSecondsGreenAssignment_6_1.eContents().get(0);
		private final Keyword cBelongsToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cBelongsToAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cBelongsToNodeCrossReference_8_0 = (CrossReference)cBelongsToAssignment_8.eContents().get(0);
		private final RuleCall cBelongsToNodeEStringParserRuleCall_8_0_1 = (RuleCall)cBelongsToNodeCrossReference_8_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Semaphore:
		//
		//	{Semaphore} "Semaphore" name=EString "{" ("canGo" canGo=EBoolean)? ("secondsRed" secondsRed=EInt)? ("secondsGreen"
		//
		//	secondsGreen=EInt)? "belongsTo" belongsTo=[Node|EString] "}";
		public ParserRule getRule() { return rule; }

		//{Semaphore} "Semaphore" name=EString "{" ("canGo" canGo=EBoolean)? ("secondsRed" secondsRed=EInt)? ("secondsGreen"
		//
		//secondsGreen=EInt)? "belongsTo" belongsTo=[Node|EString] "}"
		public Group getGroup() { return cGroup; }

		//{Semaphore}
		public Action getSemaphoreAction_0() { return cSemaphoreAction_0; }

		//"Semaphore"
		public Keyword getSemaphoreKeyword_1() { return cSemaphoreKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("canGo" canGo=EBoolean)?
		public Group getGroup_4() { return cGroup_4; }

		//"canGo"
		public Keyword getCanGoKeyword_4_0() { return cCanGoKeyword_4_0; }

		//canGo=EBoolean
		public Assignment getCanGoAssignment_4_1() { return cCanGoAssignment_4_1; }

		//EBoolean
		public RuleCall getCanGoEBooleanParserRuleCall_4_1_0() { return cCanGoEBooleanParserRuleCall_4_1_0; }

		//("secondsRed" secondsRed=EInt)?
		public Group getGroup_5() { return cGroup_5; }

		//"secondsRed"
		public Keyword getSecondsRedKeyword_5_0() { return cSecondsRedKeyword_5_0; }

		//secondsRed=EInt
		public Assignment getSecondsRedAssignment_5_1() { return cSecondsRedAssignment_5_1; }

		//EInt
		public RuleCall getSecondsRedEIntParserRuleCall_5_1_0() { return cSecondsRedEIntParserRuleCall_5_1_0; }

		//("secondsGreen" secondsGreen=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"secondsGreen"
		public Keyword getSecondsGreenKeyword_6_0() { return cSecondsGreenKeyword_6_0; }

		//secondsGreen=EInt
		public Assignment getSecondsGreenAssignment_6_1() { return cSecondsGreenAssignment_6_1; }

		//EInt
		public RuleCall getSecondsGreenEIntParserRuleCall_6_1_0() { return cSecondsGreenEIntParserRuleCall_6_1_0; }

		//"belongsTo"
		public Keyword getBelongsToKeyword_7() { return cBelongsToKeyword_7; }

		//belongsTo=[Node|EString]
		public Assignment getBelongsToAssignment_8() { return cBelongsToAssignment_8; }

		//[Node|EString]
		public CrossReference getBelongsToNodeCrossReference_8_0() { return cBelongsToNodeCrossReference_8_0; }

		//EString
		public RuleCall getBelongsToNodeEStringParserRuleCall_8_0_1() { return cBelongsToNodeEStringParserRuleCall_8_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class Signal_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Signal_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSignalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSignalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cBelongsToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBelongsToAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cBelongsToNodeCrossReference_5_0 = (CrossReference)cBelongsToAssignment_5.eContents().get(0);
		private final RuleCall cBelongsToNodeEStringParserRuleCall_5_0_1 = (RuleCall)cBelongsToNodeCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Signal_Impl returns Signal:
		//
		//	{Signal} "Signal" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
		public ParserRule getRule() { return rule; }

		//{Signal} "Signal" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}"
		public Group getGroup() { return cGroup; }

		//{Signal}
		public Action getSignalAction_0() { return cSignalAction_0; }

		//"Signal"
		public Keyword getSignalKeyword_1() { return cSignalKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"belongsTo"
		public Keyword getBelongsToKeyword_4() { return cBelongsToKeyword_4; }

		//belongsTo=[Node|EString]
		public Assignment getBelongsToAssignment_5() { return cBelongsToAssignment_5; }

		//[Node|EString]
		public CrossReference getBelongsToNodeCrossReference_5_0() { return cBelongsToNodeCrossReference_5_0; }

		//EString
		public RuleCall getBelongsToNodeEStringParserRuleCall_5_0_1() { return cBelongsToNodeEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class ExtractorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Extractor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExtractorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExtractorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cHasStartsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cHasStartsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cHasStartsSegmentCrossReference_4_2_0 = (CrossReference)cHasStartsAssignment_4_2.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_4_2_0_1 = (RuleCall)cHasStartsSegmentCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cHasStartsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cHasStartsSegmentCrossReference_4_3_1_0 = (CrossReference)cHasStartsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cHasStartsSegmentCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cHasEndsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHasEndsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cHasEndsSegmentCrossReference_7_0 = (CrossReference)cHasEndsAssignment_7.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_7_0_1 = (RuleCall)cHasEndsSegmentCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHasEndsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cHasEndsSegmentCrossReference_8_1_0 = (CrossReference)cHasEndsAssignment_8_1.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_8_1_0_1 = (RuleCall)cHasEndsSegmentCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cSemaphoreKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cSemaphoreAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cSemaphoreSemaphoreCrossReference_10_1_0 = (CrossReference)cSemaphoreAssignment_10_1.eContents().get(0);
		private final RuleCall cSemaphoreSemaphoreEStringParserRuleCall_10_1_0_1 = (RuleCall)cSemaphoreSemaphoreCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSignalsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cSignalsAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final CrossReference cSignalsSignalCrossReference_11_2_0 = (CrossReference)cSignalsAssignment_11_2.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_11_2_0_1 = (RuleCall)cSignalsSignalCrossReference_11_2_0.eContents().get(1);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cSignalsAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final CrossReference cSignalsSignalCrossReference_11_3_1_0 = (CrossReference)cSignalsAssignment_11_3_1.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_11_3_1_0_1 = (RuleCall)cSignalsSignalCrossReference_11_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Extractor:
		//
		//	{Extractor} "Extractor" name=EString "{" ("hasStarts" "(" hasStarts+=[Segment|EString] (","
		//
		//	hasStarts+=[Segment|EString])* ")")? "hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")"
		//
		//	("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] (","
		//
		//	signals+=[Signal|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Extractor} "Extractor" name=EString "{" ("hasStarts" "(" hasStarts+=[Segment|EString] (","
		//
		//hasStarts+=[Segment|EString])* ")")? "hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")"
		//
		//("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])*
		//
		//")")? "}"
		public Group getGroup() { return cGroup; }

		//{Extractor}
		public Action getExtractorAction_0() { return cExtractorAction_0; }

		//"Extractor"
		public Keyword getExtractorKeyword_1() { return cExtractorKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("hasStarts" "(" hasStarts+=[Segment|EString] ("," hasStarts+=[Segment|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"hasStarts"
		public Keyword getHasStartsKeyword_4_0() { return cHasStartsKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_4_2() { return cHasStartsAssignment_4_2; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_4_2_0() { return cHasStartsSegmentCrossReference_4_2_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_4_2_0_1() { return cHasStartsSegmentEStringParserRuleCall_4_2_0_1; }

		//("," hasStarts+=[Segment|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_4_3_1() { return cHasStartsAssignment_4_3_1; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_4_3_1_0() { return cHasStartsSegmentCrossReference_4_3_1_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_4_3_1_0_1() { return cHasStartsSegmentEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//"hasEnds"
		public Keyword getHasEndsKeyword_5() { return cHasEndsKeyword_5; }

		//"("
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_7() { return cHasEndsAssignment_7; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_7_0() { return cHasEndsSegmentCrossReference_7_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_7_0_1() { return cHasEndsSegmentEStringParserRuleCall_7_0_1; }

		//("," hasEnds+=[Segment|EString])*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_8_1() { return cHasEndsAssignment_8_1; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_8_1_0() { return cHasEndsSegmentCrossReference_8_1_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_8_1_0_1() { return cHasEndsSegmentEStringParserRuleCall_8_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }

		//("semaphore" semaphore=[Semaphore|EString])?
		public Group getGroup_10() { return cGroup_10; }

		//"semaphore"
		public Keyword getSemaphoreKeyword_10_0() { return cSemaphoreKeyword_10_0; }

		//semaphore=[Semaphore|EString]
		public Assignment getSemaphoreAssignment_10_1() { return cSemaphoreAssignment_10_1; }

		//[Semaphore|EString]
		public CrossReference getSemaphoreSemaphoreCrossReference_10_1_0() { return cSemaphoreSemaphoreCrossReference_10_1_0; }

		//EString
		public RuleCall getSemaphoreSemaphoreEStringParserRuleCall_10_1_0_1() { return cSemaphoreSemaphoreEStringParserRuleCall_10_1_0_1; }

		//("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")?
		public Group getGroup_11() { return cGroup_11; }

		//"signals"
		public Keyword getSignalsKeyword_11_0() { return cSignalsKeyword_11_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_11_2() { return cSignalsAssignment_11_2; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_11_2_0() { return cSignalsSignalCrossReference_11_2_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_11_2_0_1() { return cSignalsSignalEStringParserRuleCall_11_2_0_1; }

		//("," signals+=[Signal|EString])*
		public Group getGroup_11_3() { return cGroup_11_3; }

		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_11_3_1() { return cSignalsAssignment_11_3_1; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_11_3_1_0() { return cSignalsSignalCrossReference_11_3_1_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_11_3_1_0_1() { return cSignalsSignalEStringParserRuleCall_11_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_11_4() { return cRightParenthesisKeyword_11_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class InjectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Injector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInjectorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInjectorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCarsPerHourKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCarsPerHourAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCarsPerHourEIntParserRuleCall_4_1_0 = (RuleCall)cCarsPerHourAssignment_4_1.eContents().get(0);
		private final Keyword cHasStartsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHasStartsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cHasStartsSegmentCrossReference_7_0 = (CrossReference)cHasStartsAssignment_7.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_7_0_1 = (RuleCall)cHasStartsSegmentCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHasStartsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cHasStartsSegmentCrossReference_8_1_0 = (CrossReference)cHasStartsAssignment_8_1.eContents().get(0);
		private final RuleCall cHasStartsSegmentEStringParserRuleCall_8_1_0_1 = (RuleCall)cHasStartsSegmentCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHasEndsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cHasEndsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final CrossReference cHasEndsSegmentCrossReference_10_2_0 = (CrossReference)cHasEndsAssignment_10_2.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_10_2_0_1 = (RuleCall)cHasEndsSegmentCrossReference_10_2_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cHasEndsAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cHasEndsSegmentCrossReference_10_3_1_0 = (CrossReference)cHasEndsAssignment_10_3_1.eContents().get(0);
		private final RuleCall cHasEndsSegmentEStringParserRuleCall_10_3_1_0_1 = (RuleCall)cHasEndsSegmentCrossReference_10_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSemaphoreKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cSemaphoreAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cSemaphoreSemaphoreCrossReference_11_1_0 = (CrossReference)cSemaphoreAssignment_11_1.eContents().get(0);
		private final RuleCall cSemaphoreSemaphoreEStringParserRuleCall_11_1_0_1 = (RuleCall)cSemaphoreSemaphoreCrossReference_11_1_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cSignalsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cSignalsAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final CrossReference cSignalsSignalCrossReference_12_2_0 = (CrossReference)cSignalsAssignment_12_2.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_12_2_0_1 = (RuleCall)cSignalsSignalCrossReference_12_2_0.eContents().get(1);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cSignalsAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final CrossReference cSignalsSignalCrossReference_12_3_1_0 = (CrossReference)cSignalsAssignment_12_3_1.eContents().get(0);
		private final RuleCall cSignalsSignalEStringParserRuleCall_12_3_1_0_1 = (RuleCall)cSignalsSignalCrossReference_12_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Injector:
		//
		//	{Injector} "Injector" name=EString "{" ("carsPerHour" carsPerHour=EInt)? "hasStarts" "(" hasStarts+=[Segment|EString]
		//
		//	("," hasStarts+=[Segment|EString])* ")" ("hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])*
		//
		//	")")? ("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] (","
		//
		//	signals+=[Signal|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Injector} "Injector" name=EString "{" ("carsPerHour" carsPerHour=EInt)? "hasStarts" "(" hasStarts+=[Segment|EString]
		//
		//("," hasStarts+=[Segment|EString])* ")" ("hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])*
		//
		//")")? ("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] (","
		//
		//signals+=[Signal|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Injector}
		public Action getInjectorAction_0() { return cInjectorAction_0; }

		//"Injector"
		public Keyword getInjectorKeyword_1() { return cInjectorKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("carsPerHour" carsPerHour=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"carsPerHour"
		public Keyword getCarsPerHourKeyword_4_0() { return cCarsPerHourKeyword_4_0; }

		//carsPerHour=EInt
		public Assignment getCarsPerHourAssignment_4_1() { return cCarsPerHourAssignment_4_1; }

		//EInt
		public RuleCall getCarsPerHourEIntParserRuleCall_4_1_0() { return cCarsPerHourEIntParserRuleCall_4_1_0; }

		//"hasStarts"
		public Keyword getHasStartsKeyword_5() { return cHasStartsKeyword_5; }

		//"("
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_7() { return cHasStartsAssignment_7; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_7_0() { return cHasStartsSegmentCrossReference_7_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_7_0_1() { return cHasStartsSegmentEStringParserRuleCall_7_0_1; }

		//("," hasStarts+=[Segment|EString])*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//hasStarts+=[Segment|EString]
		public Assignment getHasStartsAssignment_8_1() { return cHasStartsAssignment_8_1; }

		//[Segment|EString]
		public CrossReference getHasStartsSegmentCrossReference_8_1_0() { return cHasStartsSegmentCrossReference_8_1_0; }

		//EString
		public RuleCall getHasStartsSegmentEStringParserRuleCall_8_1_0_1() { return cHasStartsSegmentEStringParserRuleCall_8_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }

		//("hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")")?
		public Group getGroup_10() { return cGroup_10; }

		//"hasEnds"
		public Keyword getHasEndsKeyword_10_0() { return cHasEndsKeyword_10_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_10_1() { return cLeftParenthesisKeyword_10_1; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_10_2() { return cHasEndsAssignment_10_2; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_10_2_0() { return cHasEndsSegmentCrossReference_10_2_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_10_2_0_1() { return cHasEndsSegmentEStringParserRuleCall_10_2_0_1; }

		//("," hasEnds+=[Segment|EString])*
		public Group getGroup_10_3() { return cGroup_10_3; }

		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }

		//hasEnds+=[Segment|EString]
		public Assignment getHasEndsAssignment_10_3_1() { return cHasEndsAssignment_10_3_1; }

		//[Segment|EString]
		public CrossReference getHasEndsSegmentCrossReference_10_3_1_0() { return cHasEndsSegmentCrossReference_10_3_1_0; }

		//EString
		public RuleCall getHasEndsSegmentEStringParserRuleCall_10_3_1_0_1() { return cHasEndsSegmentEStringParserRuleCall_10_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_10_4() { return cRightParenthesisKeyword_10_4; }

		//("semaphore" semaphore=[Semaphore|EString])?
		public Group getGroup_11() { return cGroup_11; }

		//"semaphore"
		public Keyword getSemaphoreKeyword_11_0() { return cSemaphoreKeyword_11_0; }

		//semaphore=[Semaphore|EString]
		public Assignment getSemaphoreAssignment_11_1() { return cSemaphoreAssignment_11_1; }

		//[Semaphore|EString]
		public CrossReference getSemaphoreSemaphoreCrossReference_11_1_0() { return cSemaphoreSemaphoreCrossReference_11_1_0; }

		//EString
		public RuleCall getSemaphoreSemaphoreEStringParserRuleCall_11_1_0_1() { return cSemaphoreSemaphoreEStringParserRuleCall_11_1_0_1; }

		//("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")?
		public Group getGroup_12() { return cGroup_12; }

		//"signals"
		public Keyword getSignalsKeyword_12_0() { return cSignalsKeyword_12_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_12_1() { return cLeftParenthesisKeyword_12_1; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_12_2() { return cSignalsAssignment_12_2; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_12_2_0() { return cSignalsSignalCrossReference_12_2_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_12_2_0_1() { return cSignalsSignalEStringParserRuleCall_12_2_0_1; }

		//("," signals+=[Signal|EString])*
		public Group getGroup_12_3() { return cGroup_12_3; }

		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }

		//signals+=[Signal|EString]
		public Assignment getSignalsAssignment_12_3_1() { return cSignalsAssignment_12_3_1; }

		//[Signal|EString]
		public CrossReference getSignalsSignalCrossReference_12_3_1_0() { return cSignalsSignalCrossReference_12_3_1_0; }

		//EString
		public RuleCall getSignalsSignalEStringParserRuleCall_12_3_1_0_1() { return cSignalsSignalEStringParserRuleCall_12_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_12_4() { return cRightParenthesisKeyword_12_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDate");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		/// * TODO: implement this rule and an appropriate IValueConverter * / EDate returns ecore::EDate:
		//
		//	STRING;
		public ParserRule getRule() { return rule; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class SpeedlimitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Speedlimit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSpeedlimitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSpeedKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSpeedAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSpeedEIntParserRuleCall_3_1_0 = (RuleCall)cSpeedAssignment_3_1.eContents().get(0);
		private final Keyword cBelongsToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBelongsToAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cBelongsToNodeCrossReference_5_0 = (CrossReference)cBelongsToAssignment_5.eContents().get(0);
		private final RuleCall cBelongsToNodeEStringParserRuleCall_5_0_1 = (RuleCall)cBelongsToNodeCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Speedlimit:
		//
		//	"Speedlimit" name=EString "{" ("Speed" Speed=EInt)? "belongsTo" belongsTo=[Node|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Speedlimit" name=EString "{" ("Speed" Speed=EInt)? "belongsTo" belongsTo=[Node|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Speedlimit"
		public Keyword getSpeedlimitKeyword_0() { return cSpeedlimitKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("Speed" Speed=EInt)?
		public Group getGroup_3() { return cGroup_3; }

		//"Speed"
		public Keyword getSpeedKeyword_3_0() { return cSpeedKeyword_3_0; }

		//Speed=EInt
		public Assignment getSpeedAssignment_3_1() { return cSpeedAssignment_3_1; }

		//EInt
		public RuleCall getSpeedEIntParserRuleCall_3_1_0() { return cSpeedEIntParserRuleCall_3_1_0; }

		//"belongsTo"
		public Keyword getBelongsToKeyword_4() { return cBelongsToKeyword_4; }

		//belongsTo=[Node|EString]
		public Assignment getBelongsToAssignment_5() { return cBelongsToAssignment_5; }

		//[Node|EString]
		public CrossReference getBelongsToNodeCrossReference_5_0() { return cBelongsToNodeCrossReference_5_0; }

		//EString
		public RuleCall getBelongsToNodeEStringParserRuleCall_5_0_1() { return cBelongsToNodeEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class StopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Stop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBelongsToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBelongsToAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cBelongsToNodeCrossReference_4_0 = (CrossReference)cBelongsToAssignment_4.eContents().get(0);
		private final RuleCall cBelongsToNodeEStringParserRuleCall_4_0_1 = (RuleCall)cBelongsToNodeCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Stop:
		//
		//	"Stop" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Stop" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Stop"
		public Keyword getStopKeyword_0() { return cStopKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"belongsTo"
		public Keyword getBelongsToKeyword_3() { return cBelongsToKeyword_3; }

		//belongsTo=[Node|EString]
		public Assignment getBelongsToAssignment_4() { return cBelongsToAssignment_4; }

		//[Node|EString]
		public CrossReference getBelongsToNodeCrossReference_4_0() { return cBelongsToNodeCrossReference_4_0; }

		//EString
		public RuleCall getBelongsToNodeEStringParserRuleCall_4_0_1() { return cBelongsToNodeEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class YieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Yield");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cYieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBelongsToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBelongsToAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cBelongsToNodeCrossReference_4_0 = (CrossReference)cBelongsToAssignment_4.eContents().get(0);
		private final RuleCall cBelongsToNodeEStringParserRuleCall_4_0_1 = (RuleCall)cBelongsToNodeCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Yield:
		//
		//	"Yield" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Yield" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Yield"
		public Keyword getYieldKeyword_0() { return cYieldKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"belongsTo"
		public Keyword getBelongsToKeyword_3() { return cBelongsToKeyword_3; }

		//belongsTo=[Node|EString]
		public Assignment getBelongsToAssignment_4() { return cBelongsToAssignment_4; }

		//[Node|EString]
		public CrossReference getBelongsToNodeCrossReference_4_0() { return cBelongsToNodeCrossReference_4_0; }

		//EString
		public RuleCall getBelongsToNodeEStringParserRuleCall_4_0_1() { return cBelongsToNodeEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private HighwayElements pHighway;
	private NodeElements pNode;
	private SignalElements pSignal;
	private Node_ImplElements pNode_Impl;
	private CarElements pCar;
	private SegmentElements pSegment;
	private SemaphoreElements pSemaphore;
	private Signal_ImplElements pSignal_Impl;
	private EStringElements pEString;
	private ExtractorElements pExtractor;
	private InjectorElements pInjector;
	private EIntElements pEInt;
	private EDateElements pEDate;
	private EBooleanElements pEBoolean;
	private SpeedlimitElements pSpeedlimit;
	private StopElements pStop;
	private YieldElements pYield;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public HighwayGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Highway".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Highway:
	//
	//	{Highway} "Highway" "{" ("Segments" "{" initSegments+=Segment ("," initSegments+=Segment)* "}")? ("Nodes" "{"
	//
	//	initNodes+=Node ("," initNodes+=Node)* "}")? ("Cars" "{" initCars+=Car ("," initCars+=Car)* "}")? ("Semaphores" "{"
	//
	//	initSemaphore+=Semaphore ("," initSemaphore+=Semaphore)* "}")? ("Signals" "{" initSignal+=Signal (","
	//
	//	initSignal+=Signal)* "}")? "}";
	public HighwayElements getHighwayAccess() {
		return (pHighway != null) ? pHighway : (pHighway = new HighwayElements());
	}
	
	public ParserRule getHighwayRule() {
		return getHighwayAccess().getRule();
	}

	//Node:
	//
	//	Node_Impl | Extractor | Injector;
	public NodeElements getNodeAccess() {
		return (pNode != null) ? pNode : (pNode = new NodeElements());
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}

	//Signal:
	//
	//	Signal_Impl | Speedlimit | Stop | Yield;
	public SignalElements getSignalAccess() {
		return (pSignal != null) ? pSignal : (pSignal = new SignalElements());
	}
	
	public ParserRule getSignalRule() {
		return getSignalAccess().getRule();
	}

	//Node_Impl returns Node:
	//
	//	{Node} "Node" name=EString "{" "hasStarts" "(" hasStarts+=[Segment|EString] ("," hasStarts+=[Segment|EString])* ")"
	//
	//	"hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")" ("semaphore"
	//
	//	semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] ("," signals+=[Signal|EString])* ")")? "}";
	public Node_ImplElements getNode_ImplAccess() {
		return (pNode_Impl != null) ? pNode_Impl : (pNode_Impl = new Node_ImplElements());
	}
	
	public ParserRule getNode_ImplRule() {
		return getNode_ImplAccess().getRule();
	}

	//Car:
	//
	//	{Car} "Car" name=EString "{" ("timeIn" timeIn=EDate)? ("timeOut" timeOut=EDate)? ("isInSegment"
	//
	//	isInSegment=[Segment|EString])? "}";
	public CarElements getCarAccess() {
		return (pCar != null) ? pCar : (pCar = new CarElements());
	}
	
	public ParserRule getCarRule() {
		return getCarAccess().getRule();
	}

	//Segment:
	//
	//	{Segment} "Segment" name=EString "{" ("numLanes" numLanes=EInt)? ("length" length=EInt)? ("hasCars" "("
	//
	//	hasCars+=[Car|EString] ("," hasCars+=[Car|EString])* ")")? "}";
	public SegmentElements getSegmentAccess() {
		return (pSegment != null) ? pSegment : (pSegment = new SegmentElements());
	}
	
	public ParserRule getSegmentRule() {
		return getSegmentAccess().getRule();
	}

	//Semaphore:
	//
	//	{Semaphore} "Semaphore" name=EString "{" ("canGo" canGo=EBoolean)? ("secondsRed" secondsRed=EInt)? ("secondsGreen"
	//
	//	secondsGreen=EInt)? "belongsTo" belongsTo=[Node|EString] "}";
	public SemaphoreElements getSemaphoreAccess() {
		return (pSemaphore != null) ? pSemaphore : (pSemaphore = new SemaphoreElements());
	}
	
	public ParserRule getSemaphoreRule() {
		return getSemaphoreAccess().getRule();
	}

	//Signal_Impl returns Signal:
	//
	//	{Signal} "Signal" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
	public Signal_ImplElements getSignal_ImplAccess() {
		return (pSignal_Impl != null) ? pSignal_Impl : (pSignal_Impl = new Signal_ImplElements());
	}
	
	public ParserRule getSignal_ImplRule() {
		return getSignal_ImplAccess().getRule();
	}

	//EString returns ecore::EString:
	//
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Extractor:
	//
	//	{Extractor} "Extractor" name=EString "{" ("hasStarts" "(" hasStarts+=[Segment|EString] (","
	//
	//	hasStarts+=[Segment|EString])* ")")? "hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])* ")"
	//
	//	("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] (","
	//
	//	signals+=[Signal|EString])* ")")? "}";
	public ExtractorElements getExtractorAccess() {
		return (pExtractor != null) ? pExtractor : (pExtractor = new ExtractorElements());
	}
	
	public ParserRule getExtractorRule() {
		return getExtractorAccess().getRule();
	}

	//Injector:
	//
	//	{Injector} "Injector" name=EString "{" ("carsPerHour" carsPerHour=EInt)? "hasStarts" "(" hasStarts+=[Segment|EString]
	//
	//	("," hasStarts+=[Segment|EString])* ")" ("hasEnds" "(" hasEnds+=[Segment|EString] ("," hasEnds+=[Segment|EString])*
	//
	//	")")? ("semaphore" semaphore=[Semaphore|EString])? ("signals" "(" signals+=[Signal|EString] (","
	//
	//	signals+=[Signal|EString])* ")")? "}";
	public InjectorElements getInjectorAccess() {
		return (pInjector != null) ? pInjector : (pInjector = new InjectorElements());
	}
	
	public ParserRule getInjectorRule() {
		return getInjectorAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	/// * TODO: implement this rule and an appropriate IValueConverter * / EDate returns ecore::EDate:
	//
	//	STRING;
	public EDateElements getEDateAccess() {
		return (pEDate != null) ? pEDate : (pEDate = new EDateElements());
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//Speedlimit:
	//
	//	"Speedlimit" name=EString "{" ("Speed" Speed=EInt)? "belongsTo" belongsTo=[Node|EString] "}";
	public SpeedlimitElements getSpeedlimitAccess() {
		return (pSpeedlimit != null) ? pSpeedlimit : (pSpeedlimit = new SpeedlimitElements());
	}
	
	public ParserRule getSpeedlimitRule() {
		return getSpeedlimitAccess().getRule();
	}

	//Stop:
	//
	//	"Stop" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
	public StopElements getStopAccess() {
		return (pStop != null) ? pStop : (pStop = new StopElements());
	}
	
	public ParserRule getStopRule() {
		return getStopAccess().getRule();
	}

	//Yield:
	//
	//	"Yield" name=EString "{" "belongsTo" belongsTo=[Node|EString] "}";
	public YieldElements getYieldAccess() {
		return (pYield != null) ? pYield : (pYield = new YieldElements());
	}
	
	public ParserRule getYieldRule() {
		return getYieldAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
