<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="highway" nsURI="highway" nsPrefix="highway">
  <eClassifiers xsi:type="ecore:EClass" name="Highway">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initNodes" ordered="false"
        upperBound="-1" eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initCars" ordered="false"
        upperBound="-1" eType="#//Car" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initSegments" ordered="false"
        upperBound="-1" eType="#//Segment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initSemaphore" ordered="false"
        upperBound="-1" eType="#//Semaphore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initSignal" ordered="false"
        upperBound="-1" eType="#//Signal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasStarts" ordered="false"
        upperBound="-1" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasEnds" ordered="false"
        upperBound="-1" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semaphore" ordered="false"
        eType="#//Semaphore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" ordered="false"
        upperBound="-1" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numLanes" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCars" ordered="false"
        upperBound="-1" eType="#//Car"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semaphore">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondsRed" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondsGreen" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canGo" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" ordered="false"
        lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" ordered="false"
        lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInSegment" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extractor" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Injector" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="carsPerHour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speedlimit" eSuperTypes="#//Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" eSuperTypes="#//Signal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Yield" eSuperTypes="#//Signal"/>
</ecore:EPackage>
